## Copyright (c) 2020-2023 The PyUnity Team
## This file is licensed under the MIT License.
## See https://docs.pyunity.x10.bz/en/latest/license.html

__all__ = ["checkModule", "getPriority", "getProviders"]

from types import ModuleType
from typing import List

_loaded: bool = ...
_names: List[str] = ...

def checkModule(name: str) -> ModuleType: ...
def getPriority(name: str) -> int: ...
def getProviders() -> List[str]: ...
