from sdl2.sdlmixer import Mix_Chunk
from .core import Component, Transform

channels: int = ...

class _CustomMock:
    def __getattr__(self, item: str) -> _CustomMock: ...
    def __setattr__(self, item: str, value: object) -> None: ...
    def __call__(self, *args, **kwargs) -> None: ...

class AudioClip:
    path: str
    music: Mix_Chunk
    def __init__(self, path: str) -> None: ...

class AudioSource(Component):
    playOnStart: bool = ...
    loop: bool = ...
    clip: AudioClip = ...

    def __init__(self, transform: Transform) -> None: ...
    def SetClip(self, clip: AudioClip) -> None: ...
    def Play(self) -> None: ...
    def Stop(self) -> None: ...
    def Pause(self) -> None: ...
    def UnPause(self) -> None: ...
    @property
    def Playing(self) -> bool: ...

class AudioListener(Component):
    opened: int
    def __init__(self, transform: Transform) -> None: ...
    def Init(self) -> None: ...
    def DeInit(self) -> None: ...