"""Module for all exceptions and warnings related to PyUnity."""

__all__ = ["PyUnityException", "ComponentException",
           "GameObjectException"]

class PyUnityException(Exception): ...
class ComponentException(PyUnityException): ...
class GameObjectException(PyUnityException): ...
