## Copyright (c) 2020-2023 The PyUnity Team
## This file is licensed under the MIT License.
## See https://docs.pyunity.x10.bz/en/latest/license.html

"""
Functions to get information about the PyUnity's installation,
distribution or build. The main function is :func:`printInfo`.

"""

from typing import IO, TYPE_CHECKING, Any, Dict, List, Tuple, Union, Callable
from importlib.metadata import Distribution

if TYPE_CHECKING:
    _Requirements = Dict[str, List[str]]
    _VersionFunc = Callable[[str], str]

def getRepoInfo() -> None: ...
def getTomlLoader() -> Tuple[Callable[[Union[IO[str], IO[bytes]]], Dict[str, Any]], str]: ...
def formatName(item: str) -> str: ...
def pruneReqs(reqs: _Requirements) -> _Requirements: ...
def getReqsFromToml(version: _VersionFunc) -> _Requirements: ...
def getReqsFromRepo(path: str, version: _VersionFunc) -> _Requirements: ...
def getReqsFromDistribution(dist: Distribution, version: _VersionFunc, gitInfo: bool = ...) -> _Requirements: ...
def printSystemInfo() -> None: ...
def getReqs() -> _Requirements: ...
def printReqs(reqs: _Requirements) -> None: ...
def printInfo() -> None: ...
