from typing import Callable, Tuple

folder: str = ...
timestamp: str = ...
start: float = ...

class Level:
    def __init__(self, abbr: str, name: str) -> None: ...
    abbr: str
    name: str

OUTPUT: Level = ...
INFO: Level = ...
DEBUG: Level = ...
ERROR: Level = ...
WARN: Level = ...

class Special:
    def __init__(self, func: Callable[[None], str]) -> None: ...
    func: Callable[[None], str]

RUNNING_TIME: Special = ...

def Log(*mesage: str) -> None: ...
def LogLine(level: Level, *message: str, silent: bool=...) -> Tuple[float, str]: ...
def LogException(e: Exception) -> None: ...
def LogSpecial(level: Level, type: Special) -> None: ...
def Save() -> None: ...
