## Copyright (c) 2020-2023 The PyUnity Team
## This file is licensed under the MIT License.
## See https://docs.pyunity.x10.bz/en/latest/license.html

from typing import Union
from pathlib import Path

directory: Path = ...
package: Path = ...
egg: bool = ...

def getPath(local: Union[str, Path]) -> Path: ...
