## Copyright (c) 2020-2023 The PyUnity Team
## This file is licensed under the MIT License.
## See https://docs.pyunity.x10.bz/en/latest/license.html

from typing import List, Optional

broken: List[int] = ...
directory: str = ...

def loadExample(i: int) -> None: ...
def show(num: Optional[int] = ...) -> None: ...
