from typing import Optional, Any

class Clock:
    _fps: int = ...
    _frameDuration: float = ...

    def __init__(self) -> None: ...
    def Start(self, fps: Optional[int] = ...) -> None: ...
    def Maintain(self) -> float: ...

    @property
    def fps(self) -> float: ...

class ImmutableStruct(type):
    def __setattr__(self, name: str, value: Any) -> None: ...
    def __delattr__(self, name: str) -> None: ...
    def _set(self, name: str, value: Any) -> None: ...
