## Copyright (c) 2020-2023 The PyUnity Team
## This file is licensed under the MIT License.
## See https://docs.pyunity.x10.bz/en/latest/license.html

"""Class to represent a rotation in 3D space."""

__all__ = ["Quaternion", "QuaternionDiff"]

from .other import LockedLiteral
from .vector import Vector3
from typing import Any, List, Tuple, Union, Iterator

class Quaternion(LockedLiteral):
    w: float
    x: float
    y: float
    z: float
    def __init__(self, w: float, x: float, y: float, z: float) -> None: ...
    def __repr__(self) -> str: ...
    def __str__(self) -> str: ...
    def __getitem__(self, i: int) -> float: ...
    def __iter__(self) -> Iterator[float]: ...
    def __list__(self) -> List[float]: ...
    def __len__(self) -> int: ...
    def __hash__(self) -> int: ...
    def __eq__(self, other: Any) -> bool: ...
    def __ne__(self, other: Any) -> bool: ...
    def __mul__(self, other: Quaternion) -> Quaternion: ...
    def __truediv__(self, other: Union[float, int]) -> Quaternion: ...
    def __sub__(self, other: Quaternion) -> QuaternionDiff: ...
    def absDiff(self, other: Quaternion) -> float: ...
    def copy(self) -> Quaternion: ...
    def normalized(self) -> Quaternion: ...
    def RotateVector(self, vector: Vector3) -> Vector3: ...

    @staticmethod
    def FromAxis(angle: float, a: Vector3) -> Quaternion: ...
    @staticmethod
    def Euler(vector: Vector3) -> Quaternion: ...
    @staticmethod
    def identity() -> Quaternion: ...
    @staticmethod
    def Between(v1: Vector3, v2: Vector3) -> Quaternion: ...
    @staticmethod
    def FromDir(v: Vector3) -> Quaternion: ...

    @property
    def conjugate(self) -> Quaternion: ...
    @property
    def angleAxisPair(self) -> Tuple[float, Vector3]: ...
    @property
    def eulerAngles(self) -> Vector3: ...

class QuaternionDiff:
    w: float
    x: float
    y: float
    z: float
    def __init__(self, w: float, x: float, y: float, z: float) -> None: ...
    def __abs__(self) -> float: ...
