from .physics.core import Collider, Manifold
from .vector3 import Vector3
from .audio import AudioClip
from .core import Component
from typing import List, Optional

class AABBoxCollider(Collider):
    def CheckOverlap(self, other: Collider) -> bool: ...
    def collidingWith(self, other: Collider) -> Optional[Manifold]: ...
    def SetSize(self, min: Vector3, max: Vector3) -> None: ...

class AudioClip:
    def SetSound(self, file: str) -> None: ...

class AudioSource(Component):
    attrs: List[str]
    def Pause(self) -> None: ...
    def Play(self) -> None: ...
    def SetClip(self, clip: AudioClip) -> None: ...
    def Stop(self) -> None: ...
    def UnPause(self) -> None: ...

class Behaviour(Component):
    attrs: List[str]

class CollManager:
    ...
